# Generated by Django 6.0.6 on 2026-06-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ropa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
