# Generated by Django 6.0.6 on 2026-06-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ropa_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
