# Generated by Django 6.0.6 on 2026-06-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_ropa_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
