# Generated by Django 6.0.6 on 2026-06-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ropa_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ropa_fotos/'),
        ),
    ]
